/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import DAO.BillDetailDAO;
import DAO.ItemDAO;
import Library.Convert;
import Model.Bill;
import Model.BillDetail;
import Model.Item;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Quang Phi
 */
public class BillDetailJDialog extends javax.swing.JDialog {

    DefaultTableModel model;
    BillDetailDAO detailDAO = new BillDetailDAO();
    Bill bill;
    ItemDAO itemDO = new ItemDAO();
    public BillDetailJDialog(java.awt.Frame parent, boolean modal,Bill bill) {
        super(parent, modal);
        initComponents();
        lblIDBill.setText("Mã hóa đơn : "+bill.getIdBill());
        lblDate.setText(Convert.formatDate(bill.getDatePayment(),"hh:mm dd/MM/yyyy"));
        this.bill = bill;
        model = (DefaultTableModel) tbTable.getModel();
        loadTable();
        setLocationRelativeTo(null);
    }
    
    private void loadTable(){
        List<BillDetail> list = detailDAO.getAllOfBill(bill.getIdBill());
        model.setRowCount(0);
        for(BillDetail billDT : list){
            Item item = itemDO.findModel(billDT.getIdItem()).get(0);
            model.addRow(new Object[]{
                model.getRowCount()+1,
                item.getItemName(),
                Convert.toMoney(billDT.getPrice()),
                item.getUnit(),
                billDT.getQuantity(),
                Convert.toMoney(billDT.sumPrice())
            });
        }
        model.addRow(new Object[]{});
        model.addRow(new Object[]{
            null,
            null,
            null,
            "Tổng phụ",
            null,
            Convert.toMoney(bill.getSumPrice())
        });
        model.addRow(new Object[]{
            null,
            null,
            null,
            "Giảm giá",
            null,
            Convert.toMoney(bill.getSale())
        });
        model.addRow(new Object[]{
            null,
            null,
            null,
            "Tổng tiền",
            null,
            Convert.toMoney(bill.getTotal())
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIDBill = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTable = new javax.swing.JTable();
        lblDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblIDBill.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        lblIDBill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIDBill.setText("Hóa đơn");

        tbTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mặt hàng", "Đơn giá", "Đơn vị tính", "Số lượng", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbTable);
        if (tbTable.getColumnModel().getColumnCount() > 0) {
            tbTable.getColumnModel().getColumn(0).setMinWidth(50);
            tbTable.getColumnModel().getColumn(0).setMaxWidth(60);
            tbTable.getColumnModel().getColumn(3).setMinWidth(70);
            tbTable.getColumnModel().getColumn(3).setMaxWidth(80);
            tbTable.getColumnModel().getColumn(4).setMinWidth(60);
            tbTable.getColumnModel().getColumn(4).setMaxWidth(70);
        }

        lblDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIDBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
            .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblIDBill, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillDetailJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillDetailJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillDetailJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillDetailJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BillDetailJDialog dialog = new BillDetailJDialog(new javax.swing.JFrame(), true,new Bill());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblIDBill;
    private javax.swing.JTable tbTable;
    // End of variables declaration//GEN-END:variables
}
