/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import DAO.EmployeesDAO;
import static Data.TableData.*;
import Data.UserData;
import Library.OptionPane;
import Main.Main;
import Model.Table;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JRadioButton;
import javax.swing.Timer;

/**
 *
 * @author ➻❥ ๖Kɦaї Ꮭε ๖➻❥003
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainJFrame() {
        initComponents();
        new Timer(1000, new ActionListener() {
            SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss a");

            @Override
            public void actionPerformed(ActionEvent e) {
                lblClock.setText(format.format(new Date()));
            }
        }).start();
    }

    private void openOrder(Table table, JRadioButton radio) {
        new OrderJDialog(this, true, table).setVisible(true);
        if (table.isEmpty()) {
            radio.setSelected(false);
        } else {
            radio.setSelected(true);
        }
    }

    private void logOut() {
        UserData.logOut();
        this.setVisible(false);
        Main.loginAndRunMainSystem(this);
    }

    private void changePassAction() {
        this.setVisible(false);
        new ChangePasswordJDialog(this, true).setVisible(true);
        if (ChangePasswordJDialog.isChanged) {
            logOut();
        } else {
            this.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel42 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel43 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel32 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel34 = new javax.swing.JPanel();
        btnChangePass = new javax.swing.JButton();
        jPanel40 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jPanel24 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        btnTable01 = new javax.swing.JLabel();
        rdoTable01 = new javax.swing.JRadioButton();
        jPanel16 = new javax.swing.JPanel();
        btnTable02 = new javax.swing.JLabel();
        rdoTable02 = new javax.swing.JRadioButton();
        jPanel17 = new javax.swing.JPanel();
        btnTable04 = new javax.swing.JLabel();
        rdoTable04 = new javax.swing.JRadioButton();
        jPanel11 = new javax.swing.JPanel();
        btnTable03 = new javax.swing.JLabel();
        rdoTable03 = new javax.swing.JRadioButton();
        jPanel18 = new javax.swing.JPanel();
        btnTable06 = new javax.swing.JLabel();
        rdoTable06 = new javax.swing.JRadioButton();
        jPanel12 = new javax.swing.JPanel();
        btnTable05 = new javax.swing.JLabel();
        rdoTable05 = new javax.swing.JRadioButton();
        jPanel19 = new javax.swing.JPanel();
        btnTable07 = new javax.swing.JLabel();
        rdoTable07 = new javax.swing.JRadioButton();
        jPanel14 = new javax.swing.JPanel();
        btnTable10 = new javax.swing.JLabel();
        rdoTable10 = new javax.swing.JRadioButton();
        jPanel13 = new javax.swing.JPanel();
        btnTable08 = new javax.swing.JLabel();
        rdoTable08 = new javax.swing.JRadioButton();
        jPanel20 = new javax.swing.JPanel();
        btnTable09 = new javax.swing.JLabel();
        rdoTable09 = new javax.swing.JRadioButton();
        jPanel15 = new javax.swing.JPanel();
        btnTable12 = new javax.swing.JLabel();
        rdoTable12 = new javax.swing.JRadioButton();
        jPanel21 = new javax.swing.JPanel();
        btnTable11 = new javax.swing.JLabel();
        rdoTable11 = new javax.swing.JRadioButton();
        jPanel23 = new javax.swing.JPanel();
        btnTable14 = new javax.swing.JLabel();
        rdoTable14 = new javax.swing.JRadioButton();
        jPanel22 = new javax.swing.JPanel();
        btnTable13 = new javax.swing.JLabel();
        rdoTable13 = new javax.swing.JRadioButton();
        jPanel26 = new javax.swing.JPanel();
        btnTable16 = new javax.swing.JLabel();
        rdoTable16 = new javax.swing.JRadioButton();
        jPanel27 = new javax.swing.JPanel();
        btnTable17 = new javax.swing.JLabel();
        rdoTable17 = new javax.swing.JRadioButton();
        jPanel25 = new javax.swing.JPanel();
        btnTable15 = new javax.swing.JLabel();
        rdoTable15 = new javax.swing.JRadioButton();
        jPanel28 = new javax.swing.JPanel();
        btnTable18 = new javax.swing.JLabel();
        rdoTable18 = new javax.swing.JRadioButton();
        jPanel39 = new javax.swing.JPanel();
        lblClock = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel31 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel41.setBackground(new java.awt.Color(243, 247, 242));
        jPanel41.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel41.setPreferredSize(new java.awt.Dimension(0, 96));
        jPanel41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel41MousePressed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconfinder_self1_62587.png"))); // NOI18N
        jButton6.setText("Quản lý kho");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 300, 80));

        jPanel42.setBackground(new java.awt.Color(243, 247, 242));
        jPanel42.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel42.setPreferredSize(new java.awt.Dimension(0, 96));
        jPanel42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel42MousePressed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/if_exit_1736.png"))); // NOI18N
        jButton3.setText("Thoát");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 300, 80));

        jPanel43.setBackground(new java.awt.Color(243, 247, 242));
        jPanel43.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel43.setPreferredSize(new java.awt.Dimension(0, 96));
        jPanel43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel43MousePressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/if_history_58875.png"))); // NOI18N
        jButton1.setText("Lịch sử");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 300, 80));

        jPanel32.setBackground(new java.awt.Color(243, 247, 242));
        jPanel32.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel32.setPreferredSize(new java.awt.Dimension(0, 96));
        jPanel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel32MousePressed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dxuat.png"))); // NOI18N
        jButton4.setText("Đăng xuất");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 300, 80));

        jPanel34.setBackground(new java.awt.Color(243, 247, 242));
        jPanel34.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel34.setPreferredSize(new java.awt.Dimension(0, 96));
        jPanel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel34MousePressed(evt);
            }
        });

        btnChangePass.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/change pass.png"))); // NOI18N
        btnChangePass.setText("Đổi mật khẩu");
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnChangePass, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnChangePass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 300, 80));

        jPanel40.setBackground(new java.awt.Color(243, 247, 242));
        jPanel40.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel40.setPreferredSize(new java.awt.Dimension(0, 96));
        jPanel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel40MousePressed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/if_purchase_order_67225.png"))); // NOI18N
        jButton9.setText("Thống kê");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 300, 80));

        jPanel24.setBackground(new java.awt.Color(243, 247, 242));
        jPanel24.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel24.setPreferredSize(new java.awt.Dimension(0, 96));
        jPanel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel24MousePressed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/if_keepassx_24076.png"))); // NOI18N
        jButton2.setText("Tài khoản");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 300, 560));

        jPanel3.setBackground(new java.awt.Color(235, 236, 236));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setBackground(new java.awt.Color(204, 0, 0));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 0, 0));
        jLabel20.setText("Hệ thống quản lý nhà hàng");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 510, 87));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 720, 130));

        jPanel4.setBackground(new java.awt.Color(255, 0, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel10.setPreferredSize(new java.awt.Dimension(120, 120));

        btnTable01.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnTable01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTable01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dinner.png"))); // NOI18N
        btnTable01.setText("Bàn 1");
        btnTable01.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTable01.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTable01.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnTable01AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnTable01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTable01MouseClicked(evt);
            }
        });

        rdoTable01.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rdoTable01.setToolTipText("");
        rdoTable01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdoTable01.setRolloverEnabled(false);
        rdoTable01.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/trangthaihd.png"))); // NOI18N
        rdoTable01.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                rdoTable01MouseMoved(evt);
            }
        });
        rdoTable01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTable01ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTable01, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
            .addComponent(rdoTable01, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(btnTable01, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoTable01)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel16.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel16.setPreferredSize(new java.awt.Dimension(120, 120));

        btnTable02.setBackground(new java.awt.Color(224, 222, 222));
        btnTable02.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnTable02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTable02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dinner.png"))); // NOI18N
        btnTable02.setText("Bàn 2");
        btnTable02.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTable02.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTable02.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnTable02AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnTable02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTable02MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTable02MousePressed(evt);
            }
        });

        rdoTable02.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rdoTable02.setToolTipText("");
        rdoTable02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdoTable02.setRolloverEnabled(false);
        rdoTable02.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/trangthaihd.png"))); // NOI18N
        rdoTable02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTable02ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTable02, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
            .addComponent(rdoTable02, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(btnTable02, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoTable02)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, -1));

        jPanel17.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel17.setPreferredSize(new java.awt.Dimension(120, 120));

        btnTable04.setBackground(new java.awt.Color(224, 222, 222));
        btnTable04.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnTable04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTable04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dinner.png"))); // NOI18N
        btnTable04.setText("Bàn 4");
        btnTable04.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTable04.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTable04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTable04MouseClicked(evt);
            }
        });

        rdoTable04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdoTable04.setRolloverEnabled(false);
        rdoTable04.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/trangthaihd.png"))); // NOI18N

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTable04, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
            .addComponent(rdoTable04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(btnTable04, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdoTable04)
                .addContainerGap())
        );

        jPanel4.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        jPanel11.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel11.setPreferredSize(new java.awt.Dimension(120, 120));

        btnTable03.setBackground(new java.awt.Color(224, 222, 222));
        btnTable03.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnTable03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTable03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dinner.png"))); // NOI18N
        btnTable03.setText("Bàn 3");
        btnTable03.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTable03.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTable03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTable03MouseClicked(evt);
            }
        });

        rdoTable03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdoTable03.setRolloverEnabled(false);
        rdoTable03.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/trangthaihd.png"))); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTable03, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
            .addComponent(rdoTable03, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(btnTable03, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdoTable03)
                .addContainerGap())
        );

        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, -1));

        jPanel18.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel18.setPreferredSize(new java.awt.Dimension(120, 120));

        btnTable06.setBackground(new java.awt.Color(224, 222, 222));
        btnTable06.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnTable06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTable06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dinner.png"))); // NOI18N
        btnTable06.setText("Bàn 6");
        btnTable06.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTable06.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTable06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTable06MouseClicked(evt);
            }
        });

        rdoTable06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdoTable06.setRolloverEnabled(false);
        rdoTable06.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/trangthaihd.png"))); // NOI18N

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTable06, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
            .addComponent(rdoTable06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(btnTable06, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdoTable06)
                .addContainerGap())
        );

        jPanel4.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        jPanel12.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel12.setPreferredSize(new java.awt.Dimension(120, 120));

        btnTable05.setBackground(new java.awt.Color(224, 222, 222));
        btnTable05.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnTable05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTable05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dinner.png"))); // NOI18N
        btnTable05.setText("Bàn 5");
        btnTable05.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTable05.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTable05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTable05MouseClicked(evt);
            }
        });

        rdoTable05.setAutoscrolls(true);
        rdoTable05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdoTable05.setRolloverEnabled(false);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTable05, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
            .addComponent(rdoTable05, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(btnTable05, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdoTable05)
                .addContainerGap())
        );

        jPanel4.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, -1, -1));

        jPanel19.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel19.setPreferredSize(new java.awt.Dimension(120, 120));

        btnTable07.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnTable07.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTable07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dinner.png"))); // NOI18N
        btnTable07.setText("Bàn 7");
        btnTable07.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTable07.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTable07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTable07MouseClicked(evt);
            }
        });

        rdoTable07.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdoTable07.setRolloverEnabled(false);
        rdoTable07.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/trangthaihd.png"))); // NOI18N

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTable07, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
            .addComponent(rdoTable07, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(btnTable07, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdoTable07)
                .addContainerGap())
        );

        jPanel4.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        jPanel14.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel14.setPreferredSize(new java.awt.Dimension(120, 120));

        btnTable10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnTable10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTable10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dinner.png"))); // NOI18N
        btnTable10.setText("Bàn 10");
        btnTable10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTable10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTable10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTable10MouseClicked(evt);
            }
        });

        rdoTable10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdoTable10.setRolloverEnabled(false);
        rdoTable10.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/trangthaihd.png"))); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rdoTable10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTable10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(btnTable10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdoTable10)
                .addContainerGap())
        );

        jPanel4.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        jPanel13.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel13.setPreferredSize(new java.awt.Dimension(120, 120));

        btnTable08.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnTable08.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTable08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dinner.png"))); // NOI18N
        btnTable08.setText("Bàn 8");
        btnTable08.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTable08.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTable08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTable08MouseClicked(evt);
            }
        });

        rdoTable08.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdoTable08.setRolloverEnabled(false);
        rdoTable08.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/trangthaihd.png"))); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTable08, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
            .addComponent(rdoTable08, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(btnTable08, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdoTable08)
                .addContainerGap())
        );

        jPanel4.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jPanel20.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel20.setPreferredSize(new java.awt.Dimension(120, 120));

        btnTable09.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnTable09.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTable09.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dinner.png"))); // NOI18N
        btnTable09.setText("Bàn 9");
        btnTable09.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTable09.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTable09.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTable09MouseClicked(evt);
            }
        });

        rdoTable09.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdoTable09.setRolloverEnabled(false);
        rdoTable09.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/trangthaihd.png"))); // NOI18N

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rdoTable09, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTable09, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(btnTable09, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdoTable09)
                .addContainerGap())
        );

        jPanel4.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        jPanel15.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel15.setPreferredSize(new java.awt.Dimension(120, 120));

        btnTable12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnTable12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTable12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dinner.png"))); // NOI18N
        btnTable12.setText("Bàn 12");
        btnTable12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTable12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTable12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTable12MouseClicked(evt);
            }
        });

        rdoTable12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdoTable12.setRolloverEnabled(false);
        rdoTable12.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/trangthaihd.png"))); // NOI18N

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTable12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
            .addComponent(rdoTable12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(btnTable12, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdoTable12)
                .addContainerGap())
        );

        jPanel4.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, -1));

        jPanel21.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel21.setPreferredSize(new java.awt.Dimension(120, 120));

        btnTable11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnTable11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTable11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dinner.png"))); // NOI18N
        btnTable11.setText("Bàn 11");
        btnTable11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTable11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTable11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTable11MouseClicked(evt);
            }
        });

        rdoTable11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdoTable11.setRolloverEnabled(false);
        rdoTable11.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/trangthaihd.png"))); // NOI18N

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rdoTable11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTable11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addComponent(btnTable11, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdoTable11)
                .addContainerGap())
        );

        jPanel4.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        jPanel23.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel23.setPreferredSize(new java.awt.Dimension(120, 120));

        btnTable14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnTable14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTable14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dinner.png"))); // NOI18N
        btnTable14.setText("Bàn 14");
        btnTable14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTable14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTable14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTable14MouseClicked(evt);
            }
        });

        rdoTable14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdoTable14.setRolloverEnabled(false);
        rdoTable14.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/trangthaihd.png"))); // NOI18N

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rdoTable14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTable14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addComponent(btnTable14, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdoTable14)
                .addContainerGap())
        );

        jPanel4.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jPanel22.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel22.setPreferredSize(new java.awt.Dimension(120, 120));

        btnTable13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnTable13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTable13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dinner.png"))); // NOI18N
        btnTable13.setText("Bàn 13");
        btnTable13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTable13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTable13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTable13MouseClicked(evt);
            }
        });

        rdoTable13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdoTable13.setRolloverEnabled(false);
        rdoTable13.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/trangthaihd.png"))); // NOI18N

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTable13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
            .addComponent(rdoTable13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addComponent(btnTable13, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdoTable13)
                .addContainerGap())
        );

        jPanel4.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        jPanel26.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel26.setPreferredSize(new java.awt.Dimension(120, 120));

        btnTable16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnTable16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTable16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dinner.png"))); // NOI18N
        btnTable16.setText("Bàn 16");
        btnTable16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTable16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTable16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTable16MouseClicked(evt);
            }
        });

        rdoTable16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdoTable16.setRolloverEnabled(false);
        rdoTable16.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/trangthaihd.png"))); // NOI18N

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTable16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
            .addComponent(rdoTable16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addComponent(btnTable16, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdoTable16)
                .addContainerGap())
        );

        jPanel4.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        jPanel27.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel27.setPreferredSize(new java.awt.Dimension(120, 120));

        btnTable17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnTable17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTable17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dinner.png"))); // NOI18N
        btnTable17.setText("Bàn 17");
        btnTable17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTable17.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTable17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTable17MouseClicked(evt);
            }
        });

        rdoTable17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdoTable17.setRolloverEnabled(false);
        rdoTable17.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/trangthaihd.png"))); // NOI18N

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTable17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
            .addComponent(rdoTable17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addComponent(btnTable17, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdoTable17)
                .addContainerGap())
        );

        jPanel4.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, -1));

        jPanel25.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel25.setPreferredSize(new java.awt.Dimension(120, 120));

        btnTable15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnTable15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTable15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dinner.png"))); // NOI18N
        btnTable15.setText("Bàn 15");
        btnTable15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTable15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTable15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTable15MouseClicked(evt);
            }
        });

        rdoTable15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdoTable15.setRolloverEnabled(false);
        rdoTable15.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/trangthaihd.png"))); // NOI18N

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTable15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
            .addComponent(rdoTable15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addComponent(btnTable15, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdoTable15)
                .addContainerGap())
        );

        jPanel4.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        jPanel28.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel28.setPreferredSize(new java.awt.Dimension(120, 120));

        btnTable18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnTable18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTable18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dinner.png"))); // NOI18N
        btnTable18.setText("Bàn 18");
        btnTable18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTable18.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTable18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTable18MouseClicked(evt);
            }
        });

        rdoTable18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdoTable18.setRolloverEnabled(false);
        rdoTable18.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/trangthaihd.png"))); // NOI18N

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rdoTable18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTable18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addComponent(btnTable18, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdoTable18)
                .addContainerGap())
        );

        jPanel4.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 720, 360));

        jPanel39.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lblClock.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblClock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Alarm.png"))); // NOI18N
        lblClock.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/if_icon-28-information_314760.png"))); // NOI18N
        jLabel21.setText("   About");

        lblUser.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/if_userconfig_7388.png"))); // NOI18N

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel39Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144)
                .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21))
                .addContainerGap())
        );

        jPanel1.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 1020, 60));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(243, 247, 242));
        jPanel9.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel9.setPreferredSize(new java.awt.Dimension(0, 96));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel9MousePressed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/if_Profile_10593.png"))); // NOI18N
        jButton7.setText("Nhân viên");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 360, 70));

        jPanel31.setBackground(new java.awt.Color(243, 247, 242));
        jPanel31.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));
        jPanel31.setPreferredSize(new java.awt.Dimension(0, 96));
        jPanel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel31MousePressed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/if_slice56_2835272.png"))); // NOI18N
        jButton8.setText("Mặt hàng");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 70));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 720, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MousePressed

    private void jPanel24MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel24MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel24MousePressed

    private void jPanel31MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel31MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel31MousePressed

    private void jPanel32MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel32MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel32MousePressed

    private void jPanel34MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel34MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel34MousePressed

    private void jPanel40MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel40MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel40MousePressed

    private void jPanel41MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel41MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel41MousePressed

    private void jPanel42MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel42MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel42MousePressed

    private void jPanel43MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel43MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel43MousePressed

    private void btnTable02MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTable02MousePressed

    }//GEN-LAST:event_btnTable02MousePressed

    private void btnTable02AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnTable02AncestorAdded

    }//GEN-LAST:event_btnTable02AncestorAdded

    private void rdoTable02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTable02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoTable02ActionPerformed

    private void rdoTable01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTable01ActionPerformed

    }//GEN-LAST:event_rdoTable01ActionPerformed

    private void rdoTable01MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoTable01MouseMoved

    }//GEN-LAST:event_rdoTable01MouseMoved

    private void btnTable01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTable01MouseClicked
        openOrder(TABLE01, rdoTable01);
    }//GEN-LAST:event_btnTable01MouseClicked

    private void btnTable01AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnTable01AncestorAdded

    }//GEN-LAST:event_btnTable01AncestorAdded

    private void btnTable02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTable02MouseClicked
        openOrder(TABLE02, rdoTable02);
    }//GEN-LAST:event_btnTable02MouseClicked

    private void btnTable03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTable03MouseClicked
        openOrder(TABLE03, rdoTable03);
    }//GEN-LAST:event_btnTable03MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        new ItemJFrame().setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnTable04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTable04MouseClicked
        openOrder(TABLE04, rdoTable04);
    }//GEN-LAST:event_btnTable04MouseClicked

    private void btnTable05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTable05MouseClicked
        openOrder(TABLE05, rdoTable05);
    }//GEN-LAST:event_btnTable05MouseClicked

    private void btnTable06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTable06MouseClicked
        openOrder(TABLE06, rdoTable06);
    }//GEN-LAST:event_btnTable06MouseClicked

    private void btnTable07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTable07MouseClicked
        openOrder(TABLE07, rdoTable07);
    }//GEN-LAST:event_btnTable07MouseClicked

    private void btnTable08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTable08MouseClicked
        openOrder(TABLE08, rdoTable08);
    }//GEN-LAST:event_btnTable08MouseClicked

    private void btnTable09MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTable09MouseClicked
        openOrder(TABLE09, rdoTable09);
    }//GEN-LAST:event_btnTable09MouseClicked

    private void btnTable10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTable10MouseClicked
        openOrder(TABLE10, rdoTable10);
    }//GEN-LAST:event_btnTable10MouseClicked

    private void btnTable11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTable11MouseClicked
        openOrder(TABLE11, rdoTable11);
    }//GEN-LAST:event_btnTable11MouseClicked

    private void btnTable12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTable12MouseClicked
        openOrder(TABLE12, rdoTable12);
    }//GEN-LAST:event_btnTable12MouseClicked

    private void btnTable13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTable13MouseClicked
        openOrder(TABLE13, rdoTable13);
    }//GEN-LAST:event_btnTable13MouseClicked

    private void btnTable14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTable14MouseClicked
        openOrder(TABLE14, rdoTable14);
    }//GEN-LAST:event_btnTable14MouseClicked

    private void btnTable15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTable15MouseClicked
        openOrder(TABLE15, rdoTable15);
    }//GEN-LAST:event_btnTable15MouseClicked

    private void btnTable16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTable16MouseClicked
        openOrder(TABLE16, rdoTable16);
    }//GEN-LAST:event_btnTable16MouseClicked

    private void btnTable17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTable17MouseClicked
        openOrder(TABLE17, rdoTable17);
    }//GEN-LAST:event_btnTable17MouseClicked

    private void btnTable18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTable18MouseClicked
        openOrder(TABLE18, rdoTable18);
    }//GEN-LAST:event_btnTable18MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new TransactionHistoryJFrame().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (!UserData.isAdmin()) {
            OptionPane.error(jButton9, "Chỉ có quản trị viên mới có thể truy cập vào chức năng này !");
        } else {
            new StatisticalJFrame().setVisible(true);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (!UserData.isAdmin()) {
            OptionPane.error(jButton2, "Chỉ có quản trị viên mới có thể truy cập vào chức năng này !");
        } else {
            new UserJFrame().setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new EmployeeJFrame().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        logOut();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        changePassAction();
    }//GEN-LAST:event_btnChangePassActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Main.turnOffSystem(this);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lblUser.setText("Tài khoản : " + UserData.getEmployees().getName());
    }//GEN-LAST:event_formWindowActivated

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new WareJFrame().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePass;
    private javax.swing.JLabel btnTable01;
    private javax.swing.JLabel btnTable02;
    private javax.swing.JLabel btnTable03;
    private javax.swing.JLabel btnTable04;
    private javax.swing.JLabel btnTable05;
    private javax.swing.JLabel btnTable06;
    private javax.swing.JLabel btnTable07;
    private javax.swing.JLabel btnTable08;
    private javax.swing.JLabel btnTable09;
    private javax.swing.JLabel btnTable10;
    private javax.swing.JLabel btnTable11;
    private javax.swing.JLabel btnTable12;
    private javax.swing.JLabel btnTable13;
    private javax.swing.JLabel btnTable14;
    private javax.swing.JLabel btnTable15;
    private javax.swing.JLabel btnTable16;
    private javax.swing.JLabel btnTable17;
    private javax.swing.JLabel btnTable18;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblUser;
    private javax.swing.JRadioButton rdoTable01;
    private javax.swing.JRadioButton rdoTable02;
    private javax.swing.JRadioButton rdoTable03;
    private javax.swing.JRadioButton rdoTable04;
    private javax.swing.JRadioButton rdoTable05;
    private javax.swing.JRadioButton rdoTable06;
    private javax.swing.JRadioButton rdoTable07;
    private javax.swing.JRadioButton rdoTable08;
    private javax.swing.JRadioButton rdoTable09;
    private javax.swing.JRadioButton rdoTable10;
    private javax.swing.JRadioButton rdoTable11;
    private javax.swing.JRadioButton rdoTable12;
    private javax.swing.JRadioButton rdoTable13;
    private javax.swing.JRadioButton rdoTable14;
    private javax.swing.JRadioButton rdoTable15;
    private javax.swing.JRadioButton rdoTable16;
    private javax.swing.JRadioButton rdoTable17;
    private javax.swing.JRadioButton rdoTable18;
    // End of variables declaration//GEN-END:variables
}
